name: "Build and release for pihole-unbound"

on:
  push:
    branches:
      - main

jobs:
  create:
    name: "Creates the newest release by version"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.4

      # New step to read the VERSION file and set the version as an output
      - name: Get the version
        id: get_version
        run: echo "pihole_unbound_version=$(cat pihole-unbound/VERSION)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            bigbeartechworld/big-bear-pihole-unbound:latest
            bigbeartechworld/big-bear-pihole-unbound:${{ env.pihole_unbound_version }}
